# Generated by Django 5.0.1 on 2024-01-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="channel_name",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
