# Generated by Django 5.0.1 on 2024-01-21 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="channel_name",
        ),
    ]
