# Generated by Django 5.0.1 on 2024-01-22 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chatmessage_channel_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
    ]
