# Generated by Django 5.0.1 on 2024-01-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="channel_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="group_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
